name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  PATH: D:\编程软件\Git\bin:$PATH

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 设置运行环境Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 16

    - name: 安装依赖
      run: npm install 
    
    - name: 构建项目
      run: npm run build

    - name: Checkout repository
      run: D:\编程软件\Git\bin\git clone <git@github.com:shake03telescope/second-vue-app.git>

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Set git config
      run: |
        git config --global user.name "telescope03shake"
        git config --global user.email "3427432494@qq.com"

    - name: 部署到pages
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        branch: wy-page
        folder: dist/

